In [26]:
import numpy as np

In [4]:
data = np.arange(2*2*2).reshape(2,2,2) #1st funciton
display(data)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
type(data)

numpy.ndarray

In [5]:
data.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
data.conjugate()

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
data.ndim

3

In [12]:
data.transpose()

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [15]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
b =a*2
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [27]:
np.sqrt(b) #2nd function 

array([[0.        , 1.41421356, 2.        ],
       [2.44948974, 2.82842712, 3.16227766],
       [3.46410162, 3.74165739, 4.        ]])

In [32]:
np.append(b , 6) #3rd function

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16,  6])

In [34]:
np.exp(b) #4th function

array([[1.00000000e+00, 7.38905610e+00, 5.45981500e+01],
       [4.03428793e+02, 2.98095799e+03, 2.20264658e+04],
       [1.62754791e+05, 1.20260428e+06, 8.88611052e+06]])

In [101]:
x = [2,4,5,6,7,8]
y = [7,6,5,4,3,2]

In [102]:
np.maximum(x , y) #5th binary universal function

array([7, 6, 5, 6, 7, 8])

In [103]:
np.power(x, y) #6th binary universal function

array([ 128, 4096, 3125, 1296,  343,   64])

In [104]:
np.square(x) #7th binary universal function

array([ 4, 16, 25, 36, 49, 64])

In [105]:
np.exp(x) #8th universal function

array([   7.3890561 ,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843, 2980.95798704])

In [106]:
np.floor(x) #9th universal function

array([2., 4., 5., 6., 7., 8.])

In [107]:
np.zeros(6) #10th universal function

array([0., 0., 0., 0., 0., 0.])

In [108]:
np.ones(3) #11th universal function

array([1., 1., 1.])

In [109]:
np.save("bcc.npy",x) #12th universal function

In [110]:
np.load("bcc.npy") #13th universal function

array([2, 4, 5, 6, 7, 8])

In [112]:
np.random.randint(0,255,(10*8*8)) #14th universal function


array([107, 114, 161, 108, 133, 136, 229,  24, 241, 184, 221, 117, 212,
        69, 218,  45, 128,  24,  12, 120,  54, 222, 182,  80,  45,  51,
       142, 209, 224, 211, 163,  22, 111,  10,  20, 142, 174,  37, 180,
         3,  44, 122, 223,  65, 187, 243, 102,  24,  57, 150, 163,  19,
       178, 120, 101, 133, 235, 117, 190, 147, 216, 131,   2, 200, 177,
        77, 101,  85,  76, 149, 244, 234, 155, 168, 209, 171, 125, 159,
        53,  61, 246, 236, 232,  15,  73, 137,  91,  58,   9, 223,  27,
       235, 193,  87,  75,  13, 110, 130,  95, 146,  16, 143, 210, 241,
        31, 221, 233, 129,  66, 198,  87, 165,  52, 232,  27,  23, 213,
        36, 135, 253,  32, 230, 116,  15,  47,  37,  80, 237, 103, 130,
         5,  94, 203, 123,  81,  89, 209,  98, 197, 112, 124,  19, 139,
       252, 204, 138,  66, 157,  80, 102, 163, 219, 246,  94, 239,  34,
        18, 248, 195,  62, 187,   0, 125, 129, 139, 188, 160, 195,  63,
        61, 154, 134,  26, 181, 112, 232,  57, 126,  23,   9,  1

In [114]:
z = np.array([10,24,43,64,13,10,9])

In [116]:
z.sort()
z

array([ 9, 10, 10, 13, 24, 43, 64])

In [118]:
g = np.concatenate((a,b)) #15th universal function
g  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [121]:
np.diff(z) #16th universal function

array([ 1,  0,  3, 11, 19, 21])

In [125]:
#find lcm
num1 = 4
num2 = 5
np.lcm(num1, num2) #17th universal function

20

In [129]:
#find hcf
np.gcd(num1, num2) #18th universal function

1

In [130]:
np.sin(z)

array([ 0.41211849, -0.54402111, -0.54402111,  0.42016704, -0.90557836,
       -0.83177474,  0.92002604])

In [131]:
np.unique(z) #19th universal function

array([ 9, 10, 13, 24, 43, 64])

In [132]:
f = np.array([2,3,23,4,32,4,2,2,2,4,5,5,6,2,1])

In [134]:
np.union1d(f, z) #20th universal function

array([ 1,  2,  3,  4,  5,  6,  9, 10, 13, 23, 24, 32, 43, 64])